# Generated by Django 3.1.5 on 2021-09-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='The Latitude Coordinate.', max_digits=12, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='state',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='The Longitude Coordinate.', max_digits=12, null=True, verbose_name='Longitude'),
        ),
    ]
